import turtle

t = turtle.Turtle()
t3 = turtle.Turtle()
t3.hideturtle()
screen = turtle.Screen()
screen.setup(800,800)
screen.bgcolor("hot pink")
t.write("My presentation by Jules", font=("Arial", 24, "bold"), align="center")
turtle.addshape("ocean.gif")
t3.penup()
t3.goto(0,100)
t3.shape("ocean.gif")
a= t3.stamp()
t.penup()
t.goto(50,-200)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
t.circle(25)
t.end_fill()
t.penup()
t.goto(-100,100)


enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("purple")
t.penup()
t.goto(-100,-100)
t.pendown()
t.fillcolor("white")
t.begin_fill()
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.forward(25)
t.left(90)
t.penup()
t.goto(-100,175)
t.pendown()
t.write("My Favorite Foods", font=("Arial", 24, "bold"), align="center")
turtle.addshape("alfredo.gif")
t3.shape("alfredo.gif")
b = t3.stamp()
t3.goto(150,75)
turtle.addshape("fries.gif")
t3.shape("fries.gif")
c = t3.stamp()
t3.goto(80,80)
turtle.addshape("catfish.gif")
t3.shape("catfish.gif")
d = t3.stamp()
t.end_fill()

enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("purple")
t.write("My Hobbies", font=("Arial", 24, "bold"), align="center")
turtle.addshape("softball.gif")
t3.shape("softball.gif")
e = t3.stamp()
t3.goto(250,10)
turtle.addshape("fortnite.gif")
t3.shape("fortnite.gif")
f = t3.stamp()
t3.goto(15,-75)
turtle.addshape("disney.gif")
t3.shape("disney.gif")
g = t3.stamp()
t3.goto(100,50)
turtle.addshape("cleaning.gif")
t3.shape("cleaning.gif")
h = t3.stamp()
t.penup()
t.goto(-150,-150)
t.pendown()
t.fillcolor("White")
t.begin_fill()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()

enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("teal")
t.penup()
t.goto(-100,175)
t.pendown()
t.write("Favorite Movie", font=("Arial", 24, "bold"), align="center")
t.penup()
turtle.addshape("moana.gif")
t3.shape("moana.gif")
i = t3.stamp()
t.goto(-25,15)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(25)
t.left(90)
t.forward(50)
t.left(90)
t.forward(25)
t.left(90)
t.end_fill()

enter = input("Press enter to begin")
t.clear()
t3.clearstamps()
screen.bgcolor("red")
t3.goto(180,-65)
t.penup()
t.goto(-100,175)
t.pendown()
t.write("Favorite Sport", font=("Arial", 24, "bold"), align="center")
t3.goto(180,65)
turtle.addshape("huddle.gif")
t3.shape("huddle.gif")
i = t3.stamp()
t.penup()
t.goto(-15,75)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
t.setheading(45)
t.forward(50)
t.setheading(135)
t.forward(50)
t.setheading(270)
t.forward(75)
t.end_fill()

turtle.done()